/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_SystemInfo */

#ifndef _Included_jni_SystemInfo
#define _Included_jni_SystemInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_SystemInfo
 * Method:    getMemoryInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_SystemInfo_getMemoryInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
