cc_binary(
    name = "cel_example",
    srcs = ["cel_example.cc"],
    deps = [
        "@cel-cpp//eval/public:activation",
        "@cel-cpp//eval/public:cel_expr_builder_factory",
        "@cel-cpp//eval/public:builtin_func_registrar",
        "@cel-cpp//eval/public:cel_expression",
        "@cel-cpp//eval/public:cel_options",
        "@cel-cpp//eval/public:cel_value",
        "@cel-cpp//parser",
        "@abseil-cpp//absl/status",
        "@protobuf//:protobuf",
    ],
)
